language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt --upgrade
  - pip install --upgrade pylint
  - python setup.py develop
  - python install-testplan-ui --verbose --dev

script:
  - pylint --rcfile pylintrc testplan
  - py.test test --verbose

